import type { FloatrSkillManifest } from "./skills-types";

const FLOATR_NATIVE_SOURCE = {
  repoUrl: "https://github.com/floatr/skills",
  commitSha: "builtin",
  license: "MIT",
  trust: "floatr_native" as const,
};

export const DEFAULT_SKILLS: FloatrSkillManifest[] = [
  {
    schemaVersion: 1,
    id: "karpathy-doctrine",
    name: "Karpathy Doctrine",
    class: "doctrine",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Coding doctrine favoring explicit assumptions, simplicity, surgical edits, and verifiable success criteria.",
    triggers: {
      tasks: ["build", "debug", "refactor", "review"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode", "bolt", "api"] },
    instructions: {
      system: [
        "State assumptions explicitly before starting any implementation.",
        "Prefer the smallest possible change that solves the problem.",
        "Avoid unrelated edits — if you notice something else, note it separately.",
        "Define what done looks like before writing code.",
        "Think step by step before producing output.",
        "When uncertain, ask a clarifying question rather than guessing.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment", "cockpit_badge"] },
    cost: { tokenOverheadEstimate: 180 },
    rankingHints: { taskFitWeight: 0.9, repoFitWeight: 0.5, measuredLiftWeight: 1.0 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "flow-router",
    name: "Flow Router",
    class: "workflow",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Structured plan → build → verify → ship workflow with routing for different task types.",
    triggers: {
      tasks: ["build", "refactor", "debug"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "For any non-trivial task, follow: Plan → Build → Verify → Ship.",
        "In the Plan phase: state the goal, list the files that will change, and identify any risks.",
        "In the Build phase: implement one change at a time, verify each step before proceeding.",
        "In the Verify phase: check that the success criteria from the Plan phase are met.",
        "For debug tasks: reproduce first, then isolate, then fix, then confirm fix.",
        "For review tasks: summarize changes, identify blast radius, flag regressions.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 220 },
    rankingHints: { taskFitWeight: 1.0, repoFitWeight: 0.4, measuredLiftWeight: 0.8 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "memory-compact",
    name: "Memory Compact",
    class: "context",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Cross-session memory context injection — retrieves the most relevant past observations into system prompt.",
    triggers: {
      tasks: ["build", "debug", "refactor", "explore"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw"] },
    instructions: {
      system: [
        "Relevant context from past sessions is injected at the start of this session.",
        "Use past observations to avoid repeating work already done.",
        "If past context seems outdated or contradicted by current state, note the discrepancy.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 120 },
    rankingHints: { taskFitWeight: 0.7, repoFitWeight: 0.6, measuredLiftWeight: 0.9 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "lean-compression",
    name: "Lean Compression",
    class: "efficiency",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Response compression profile — reduces token usage by tightening response style.",
    triggers: {
      tasks: ["build", "debug", "refactor", "review", "explore", "team"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode", "bolt"] },
    instructions: {
      system: [
        "Be concise. Skip preamble and filler phrases.",
        "Omit restating the question unless it helps clarity.",
        "Use bullet points over paragraphs for lists of items.",
        "Show code without wrapping it in explanation unless the explanation is genuinely useful.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 80 },
    rankingHints: { taskFitWeight: 0.5, repoFitWeight: 0.3, measuredLiftWeight: 0.7 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "focused-memory",
    name: "Focused Memory",
    class: "context",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Retrieves only the most directly relevant past observations — lower token cost than Memory Compact.",
    triggers: {
      tasks: ["debug", "review", "refactor"],
      repoKinds: ["any"],
      sessionModes: ["solo"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw"] },
    instructions: {
      system: [
        "A focused set of past observations most relevant to the current task has been injected.",
        "Use this context to avoid re-discovering known facts about the codebase.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 60 },
    rankingHints: { taskFitWeight: 0.8, repoFitWeight: 0.5, measuredLiftWeight: 0.7 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "one-line-review",
    name: "One-Line Review Mode",
    class: "efficiency",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Maximally terse review output — one actionable line per file or issue.",
    triggers: {
      tasks: ["review"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "For code review, produce one line of feedback per file or issue.",
        "Format: [SEVERITY] filename:line — description. Example: [WARN] auth.ts:42 — token not validated before use.",
        "Severity levels: CRIT, WARN, INFO, STYLE.",
        "Omit commentary on correct code. Only flag actionable issues.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 90 },
    rankingHints: { taskFitWeight: 1.0, repoFitWeight: 0.3, measuredLiftWeight: 0.8 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "debug-flow",
    name: "Debug Flow",
    class: "workflow",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Structured debugging workflow: reproduce → isolate → fix → confirm.",
    triggers: {
      tasks: ["debug"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "Debug workflow: Reproduce → Isolate → Fix → Confirm.",
        "Step 1 Reproduce: get a minimal reproducible case before touching any code.",
        "Step 2 Isolate: binary search the call stack or data path until the exact fault is found.",
        "Step 3 Fix: make only the change needed to fix the fault. Do not refactor during debug.",
        "Step 4 Confirm: re-run the reproduction case and verify it passes.",
        "If you cannot reproduce the bug, say so clearly and list what you tried.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 200 },
    rankingHints: { taskFitWeight: 1.0, repoFitWeight: 0.4, measuredLiftWeight: 0.9 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "checkpoints-lite",
    name: "Checkpoints Lite",
    class: "workflow",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Lightweight checkpoint pattern — placeholder; full implementation in Phase 2.",
    triggers: {
      tasks: ["debug", "build", "refactor"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw"] },
    instructions: {
      system: [
        "Before making a complex multi-step change, summarize the current state in one sentence.",
        "After each major step, confirm what changed and whether it worked before moving on.",
        "If something goes wrong mid-task, state clearly which step failed and what the rollback plan is.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 100 },
    rankingHints: { taskFitWeight: 0.7, repoFitWeight: 0.4, measuredLiftWeight: 0.6 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "compact-response",
    name: "Compact Response",
    class: "efficiency",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Minimal response style for debug and fix tasks — error + fix only, no narration.",
    triggers: {
      tasks: ["debug", "refactor"],
      repoKinds: ["any"],
      sessionModes: ["solo"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "For bug reports or errors: state the cause in one sentence, then show the fix.",
        "No narration before or after the fix. No 'Here is the updated code:' headers.",
        "If multiple files change, show each as a separate code block with the filename above it.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 70 },
    rankingHints: { taskFitWeight: 0.8, repoFitWeight: 0.3, measuredLiftWeight: 0.7 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "shared-memory-lite",
    name: "Shared Memory Lite",
    class: "context",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Team session memory — placeholder; full shared-workspace memory tree in Phase 3.",
    triggers: {
      tasks: ["build", "review", "debug", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "This is a team session. Multiple developers are working in the same environment.",
        "Before making changes to shared code, note what you are changing and why.",
        "Prefer small, well-scoped commits so teammates can follow your work.",
        "If you see work in progress by another developer, do not overwrite it without checking.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 110 },
    rankingHints: { taskFitWeight: 0.6, repoFitWeight: 0.4, measuredLiftWeight: 0.5 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "decision-log-lite",
    name: "Decision Log Lite",
    class: "workflow",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Lightweight architectural decision logging — placeholder; full ADR system in Phase 3.",
    triggers: {
      tasks: ["build", "refactor", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "vscode"] },
    instructions: {
      system: [
        "When making an architectural decision, briefly note: what you chose, what you rejected, and why.",
        "Format: DECISION: <choice> | REJECTED: <alternative> | REASON: <why>.",
        "This helps teammates understand past decisions without digging through history.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 90 },
    rankingHints: { taskFitWeight: 0.5, repoFitWeight: 0.4, measuredLiftWeight: 0.5 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "context-shield-core",
    name: "Context Shield",
    class: "efficiency",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Routes high-output operations through bounded subprocesses so compact summaries — not raw dumps — reach the model context.",
    triggers: {
      tasks: ["debug", "review", "build", "refactor", "explore"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw"] },
    instructions: {
      system: [
        "A shielded execution runtime is available on this instance. Use it for any command that may produce large output.",
        "Use `floatr_execute <command>` instead of bare bash for: grep/rg/find, test runners, build commands, git log/diff/blame, and any command likely to produce >200 lines.",
        "When floatr_execute returns a summary with an artifact path, reference the artifact path rather than re-running the command.",
        "Use `floatr_execute_file <path>` instead of `cat` or `read_file` for files larger than a few hundred lines — you will receive a compact summary and the artifact path.",
        "Use `floatr_batch_execute '[{\"cmd\":\"...\"}]'` to run multiple commands in one shielded call and receive a single summary.",
        "If a command is blocked by the shield (HTTP 403 response), do not attempt to bypass the safety check — report the block and suggest an alternative approach.",
        "Execution errors return HTTP 500. HTTP 200 means success (shielded or inline). 403 means dangerous pattern blocked.",
        "Shielded output is saved to /workspace/.floatr/artifacts/ and is available for the duration of the session.",
        "Run `floatr_stats` to see routing metrics, bytes avoided, per-class routing breakdown, and failure counts.",
        "Run `floatr_doctor` to check shield health including stale snapshot detection and routing failure diagnostics.",
        "Before a context compaction event, POST to /floatr/compact to save a snapshot and prime the restore path.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 250 },
    rankingHints: { taskFitWeight: 0.9, repoFitWeight: 0.5, measuredLiftWeight: 1.0 },
    safety: { shellExecution: "restricted", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "working-state-continuity",
    name: "Working State Continuity",
    class: "context",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Preserves task progress across compaction and reconnects — active task, plan checkpoint, active files, and unresolved errors survive context resets.",
    triggers: {
      tasks: ["build", "debug", "refactor", "review", "explore"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw"] },
    instructions: {
      system: [
        "This session has working state continuity. A per-session event journal is stored at /workspace/.floatr/session-state.db.",
        "At the start of each task, a restore block may be injected from the latest snapshot — use it to pick up where the previous task left off without re-reading the entire codebase.",
        "Before any compaction or major context reset, signal the Claw Runner via POST /floatr/compact with your current working state (activeTask, planCheckpoint, activeFiles, unresolvedErrors, bundleSlug, tokenMode). This saves a snapshot AND primes the next task start to force-inject the restore block via the compaction path.",
        "Use POST /floatr/snapshot for manual saves between compaction events. Both endpoints accept the same payload.",
        "Keep snapshots concise: one sentence per active task, a bulleted plan checkpoint, and a list of at most 5 active file paths.",
        "Log plan changes via POST /floatr/plan with {checkpoint, activeFiles, taskSummary} — this updates the event journal and the active state.",
        "Log tool use and tool results via POST /floatr/event with {event_type, payload}. Allowed types: tool_use, tool_result, plan_change, plan_checkpoint, user_note, error_observed, decision, task_progress.",
        "After restoring from a snapshot, validate its fields against the current filesystem state before using them — the snapshot may be stale if files changed.",
        "Use GET /floatr/restore to read the current snapshot and recent events without starting a task.",
        "Working state is in-session only. For cross-session memory, use the memory layer (memory-compact or focused-memory skills).",
        "If no snapshot is available at task start, proceed normally — continuity is best-effort and never blocks execution.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 300 },
    rankingHints: { taskFitWeight: 1.0, repoFitWeight: 0.4, measuredLiftWeight: 0.9 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "memory-governance-core",
    name: "Memory Governance Core",
    class: "context",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Progressive-disclosure memory retrieval with contradiction awareness, staleness tracking, ROI promotion, and team-aware scope resolution for long-running and shared sessions.",
    triggers: {
      tasks: ["build", "debug", "review", "refactor", "explore", "team"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "Use the three-layer memory protocol: start with GET /mem/index (Layer 1) for the top-5 high-ROI items; escalate to GET /mem/search?q=<query> (Layer 2) when you need richer context; use GET /mem/item/:id?escalate=true (Layer 3) only for a specific item when the first two layers are insufficient.",
        "Before saving a new memory item, be aware that POST /mem/item runs automatic contradiction detection. If the response includes hasConflict=true, surface the conflicting item IDs to the user before proceeding.",
        "Prefer storing factual conventions and guardrails over transient observations — conventions and guardrails have the longest TTL and highest injection priority.",
        "Respect the scope hierarchy when scoping a save: task (most local) → lane_user → repo_shared → session_core → user_operator → global (most shared). Use the narrowest scope that makes sense for the information.",
        "Stale items (stale_status='stale') can still be searched but are deprioritized for injection. Do not re-inject stale items without checking their recency.",
        "After completing a significant task segment, call POST /mem/item with memoryType='session_summary' to persist the outcome for future sessions.",
        "For team sessions, prefer scope='repo_shared' for decisions that affect the whole team's codebase.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 260 },
    rankingHints: { taskFitWeight: 0.9, repoFitWeight: 0.5, measuredLiftWeight: 1.2 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "budgeted-retrieval",
    name: "Budgeted Retrieval",
    class: "efficiency",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Token-mode-aware memory budget enforcement — controls candidate count, layer availability, stale suppression, and metadata verbosity to keep context injection within budget.",
    triggers: {
      tasks: ["build", "debug", "refactor", "explore", "team"],
      repoKinds: ["any"],
      sessionModes: ["solo", "team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "Always pass tokenMode=<current_mode> to all /mem/* endpoints so the server applies the correct budget profile.",
        "In 'ultra' or 'lean' mode, use only Layer 1 (GET /mem/index) for memory context — Layer 2 and 3 are budget-restricted in these modes.",
        "In 'ultra' mode, include at most 3 memory items in context; in 'lean' at most 5; in 'core' at most 10; in 'full' at most 20.",
        "Omit metadata fields (scope, roiScore, conflictStatus) when memoryMetadataVerbosity is 'compact' — include only content and memoryType.",
        "Do not surface contradiction warnings to the user when memoryContradictionSurfacing is 'off'. When it is 'hint', note the conflict count without detail.",
        "Call GET /mem/stats?userId=<id>&tokenMode=<mode> at session start to understand the current budget profile and total item counts before planning retrieval.",
        "After injecting memory items into context, call POST /mem/injected with the item IDs to update ROI scores and enable auto-promotion.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 200 },
    rankingHints: { taskFitWeight: 0.8, repoFitWeight: 0.3, measuredLiftWeight: 1.0 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  // ── Team coordination skills ─────────────────────────────────────────────────
  {
    schemaVersion: 1,
    id: "team-coordination-core",
    name: "Team Coordination Core",
    class: "team",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Core coordination layer for multi-lane team sessions — session efficiency rules, contention management, and cross-lane communication protocols.",
    triggers: {
      tasks: ["build", "review", "debug", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "This is a team session with multiple active lanes (one per team member). Each lane runs its own overlay bundle — you are in your own lane.",
        "The session core (this skill) is the only layer shared across all lanes. Overlay bundles are strictly lane-local.",
        "Before writing to a shared module or API, check GET /api/sessions/:id/conflicts for overlap warnings with other lanes.",
        "Use POST /api/sessions/:id/lanes/:laneId/handoff to signal state to other lanes: blocked, needs_review, safe_to_merge, watch_files, or related_lane.",
        "When GPU-expensive work is needed (graph rebuild, embedding refresh, deep log analysis), schedule via POST /api/sessions/:id/heavy-jobs rather than running inline.",
        "Prefer small, well-scoped changes while other lanes are active to minimize blast-radius overlap.",
        "Claim files you are editing via POST /api/sessions/:id/lanes/:laneId/claim so other lanes can detect ownership early.",
        "Refresh claim heartbeats every few minutes via DELETE .../:claimId?heartbeat=true to keep claims alive.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 260 },
    rankingHints: { taskFitWeight: 1.0, repoFitWeight: 0.5, measuredLiftWeight: 1.2 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "lane-awareness",
    name: "Lane Awareness",
    class: "team",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Per-member lane overlay awareness — injects lane type, task ownership, and retrieval emphasis into the member's own prompt path only.",
    triggers: {
      tasks: ["build", "debug", "review", "refactor", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "Your lane overlay is injected only into your own prompt path — other team members do not see it.",
        "Use GET /api/sessions/:id/lanes to see all active lanes and what each member is currently working on.",
        "Use GET /api/sessions/:id/coordination for a full view of active lanes, claims, and recent handoffs.",
        "Before starting a task that touches shared code, check whether another lane has claimed those files.",
        "Scope your memory saves narrowly: use scope='lane_user' for working state personal to you, scope='repo_shared' for facts relevant to all team members, and scope='task' for the current task only.",
        "Your lane type determines your default retrieval emphasis — prioritize context matching your lane's focus area.",
        "When done with a task segment, update your lane status via PUT /api/sessions/:id/lanes/:laneId with status='ready-to-merge' or 'review-needed'.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 200 },
    rankingHints: { taskFitWeight: 0.9, repoFitWeight: 0.4, measuredLiftWeight: 1.0 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "shared-repo-memory",
    name: "Shared Repo Memory",
    class: "team",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Shared architectural knowledge layer — reuses repo graph, architecture summary, and conventions across all lanes without duplicating context per member.",
    triggers: {
      tasks: ["build", "review", "debug", "refactor", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "Architectural facts, coding conventions, and repo-level guardrails are stored in scope='repo_shared' — accessible to all team members.",
        "Before recording a new architectural decision, search scope='repo_shared' via GET /mem/search to avoid duplicating existing conventions.",
        "Store architectural decisions, API contracts, schema changes, and shared guardrails as scope='repo_shared' with memoryType='convention' or 'guardrail'.",
        "Personal working state (active files, task progress, debug traces) should stay in scope='lane_user' or 'task' — do not promote transient state to repo_shared.",
        "After a significant refactor or API change, scan for stale repo_shared items via POST /mem/symbol-stale to trigger stale-status marking.",
        "Retrieval order: task → lane_user → repo_shared → session_core → user_operator → global. Shared architectural facts always rank below your own task-specific context.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 220 },
    rankingHints: { taskFitWeight: 0.8, repoFitWeight: 0.7, measuredLiftWeight: 1.1 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "contention-management-core",
    name: "Contention Management Core",
    class: "team",
    source: FLOATR_NATIVE_SOURCE,
    summary: "GPU contention and heavy-job fairness — schedules expensive coordination tasks through the weighted fair queue to prevent starvation of background indexing by foreground work.",
    triggers: {
      tasks: ["build", "debug", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "GPU-expensive operations (repo indexing, embedding refresh, eval harnesses, blast-radius analysis, bundle compilation) must be scheduled via the heavy-job queue, not run inline.",
        "To schedule a heavy job: POST /api/sessions/:id/heavy-jobs with {jobClass, priority, laneId, payload}.",
        "Valid jobClass values: 'indexing' (repo graph rebuild, priority 3-7), 'embedding' (vector refresh, 2-5), 'eval' (skill eval harness, 4-8), 'blast_radius' (dependency impact, 3-6), 'compile' (bundle compilation, 2-5), 'other' (1-5).",
        "Do not set priority > 8 for background indexing — this would starve lower-priority lane work.",
        "Poll GET /api/sessions/:id/heavy-jobs?status=queued,running to see the current queue (ordered by scheduler score) before scheduling new expensive work.",
        "Use PATCH /api/sessions/:id/heavy-jobs/:jobId with {status:'running'|'completed'|'failed'|'deferred', result?, errorMessage?} to update job progress.",
        "Background indexing jobs have starvation protection built in (age weight + class floor) — they will eventually run even at lower priority.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 180 },
    rankingHints: { taskFitWeight: 0.7, repoFitWeight: 0.4, measuredLiftWeight: 0.9 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
  {
    schemaVersion: 1,
    id: "handoff-discipline",
    name: "Handoff Discipline",
    class: "team",
    source: FLOATR_NATIVE_SOURCE,
    summary: "Structured handoff signals between lanes — blocked, needs_review, safe_to_merge, watch_files, and related_lane types with optional free-text context.",
    triggers: {
      tasks: ["build", "review", "team"],
      repoKinds: ["any"],
      sessionModes: ["team"],
    },
    compatibility: { models: ["kimi", "qwen", "glm", "deepseek", "minimax"], interfaces: ["claw", "api"] },
    instructions: {
      system: [
        "Use structured handoff signals — not free-text messages — to communicate state changes to other lanes.",
        "Handoff types: 'blocked' (waiting on another lane), 'needs_review' (ready for peer review), 'safe_to_merge' (green light to integrate), 'watch_files' (flag files about to change), 'related_lane' (link lanes working on the same feature).",
        "To signal: POST /api/sessions/:id/lanes/:laneId/handoff with {handoffType, message?, toLaneIds?, resourcePaths?}.",
        "Use 'watch_files' before editing a file another lane might be reading — include the file paths in resourcePaths.",
        "Use 'blocked' with a message explaining what you are waiting for so other lanes can act on it.",
        "Use 'safe_to_merge' only when your changes are fully tested and do not conflict with known claims from other lanes.",
        "To target a specific lane: include its ID in toLaneIds. Omit toLaneIds to broadcast to all session lanes.",
        "Check GET /api/sessions/:id/coordination regularly for handoff signals directed at or related to your lane.",
        "After receiving a 'needs_review' signal, acknowledge it by updating the requesting lane's status via PUT /api/sessions/:id/lanes/:laneId.",
      ],
    },
    install: { type: "virtual", outputs: ["system_prompt_fragment"] },
    cost: { tokenOverheadEstimate: 220 },
    rankingHints: { taskFitWeight: 0.8, repoFitWeight: 0.3, measuredLiftWeight: 1.0 },
    safety: { shellExecution: "none", networkAccess: "none" },
  },
];

export interface DefaultBundleSpec {
  slug: string;
  name: string;
  skillIds: string[];
  taskMode: string;
  sessionMode: string;
  description: string;
}

export const DEFAULT_BUNDLES: DefaultBundleSpec[] = [
  {
    slug: "floatr-builder",
    name: "FLOATR Builder",
    skillIds: ["karpathy-doctrine", "flow-router", "memory-compact", "lean-compression", "context-shield-core", "working-state-continuity"],
    taskMode: "build",
    sessionMode: "solo",
    description: "Default bundle for building new features — doctrine + flow + memory + compression + context shield + continuity.",
  },
  {
    slug: "floatr-reviewer",
    name: "FLOATR Reviewer",
    skillIds: ["karpathy-doctrine", "flow-router", "focused-memory", "one-line-review", "context-shield-core"],
    taskMode: "review",
    sessionMode: "solo",
    description: "Code review bundle — doctrine + flow + focused memory + terse review output + context shield.",
  },
  {
    slug: "floatr-debugger",
    name: "FLOATR Debugger",
    skillIds: ["debug-flow", "checkpoints-lite", "focused-memory", "compact-response", "context-shield-core", "working-state-continuity"],
    taskMode: "debug",
    sessionMode: "solo",
    description: "Debugging bundle — structured debug flow + checkpoints + focused memory + compact output + shield + continuity.",
  },
  {
    slug: "floatr-team-studio",
    name: "FLOATR Team Studio",
    skillIds: ["shared-memory-lite", "flow-router", "decision-log-lite", "lean-compression", "context-shield-core", "working-state-continuity"],
    taskMode: "team",
    sessionMode: "team",
    description: "Team session bundle — shared memory + flow + decision log + lean compression + shield + continuity.",
  },
  {
    slug: "floatr-team-coordination",
    name: "FLOATR Team Coordination",
    skillIds: ["team-coordination-core", "lane-awareness", "shared-repo-memory", "contention-management-core", "handoff-discipline", "memory-governance-core"],
    taskMode: "team",
    sessionMode: "team",
    description: "Multi-lane team coordination bundle — session core, lane overlay, shared repo memory, heavy-job contention, handoff discipline, and governance.",
  },
];
