import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import sessionsRouter from "./sessions";
import templatesRouter from "./templates";
import offersRouter from "./offers";
import dashboardRouter from "./dashboard";
import schedulerRouter from "./scheduler";
import memoryRouter from "./memory";
import skillsRouter from "./skills";
import repoRouter, { batchRepoRouter } from "./repo";
import coordinationRouter from "./coordination";
import designIntelligenceRouter from "./design-intelligence";
import ambientRouter from "./ambient";
import paletteIntentRouter from "./palette-intent";
import nimRouter from "./nim";
import authRouter from "./auth";
import bridgeRouter from "./bridge";
import orchestrateRouter from "./orchestrate";
import intentRouter from "./intent";
import schemaTemplatesRouter from "./schema-templates";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(profilesRouter);
router.use(sessionsRouter);
router.use(templatesRouter);
router.use(offersRouter);
router.use(dashboardRouter);
router.use(schedulerRouter);
router.use(memoryRouter);
router.use(skillsRouter);
router.use("/sessions/repo", batchRepoRouter);
router.use("/sessions/:sessionId/repo", repoRouter);
router.use(coordinationRouter);
router.use(designIntelligenceRouter);
router.use(ambientRouter);
router.use(paletteIntentRouter);
router.use(nimRouter);
router.use(intentRouter);
router.use(bridgeRouter);
router.use(orchestrateRouter);
router.use(schemaTemplatesRouter);

export default router;
