// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/CommandCenter.tsx": () => import("../components/mockups/dashboard-redesign/CommandCenter.tsx"),
  "./components/mockups/dashboard-redesign/LauncherFirst.tsx": () => import("../components/mockups/dashboard-redesign/LauncherFirst.tsx"),
  "./components/mockups/dashboard-redesign/TwoColumn.tsx": () => import("../components/mockups/dashboard-redesign/TwoColumn.tsx")
};
